// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrganizationMember = `-- name: AddOrganizationMember :exec
INSERT INTO organization_members (user_id, organization_id)
VALUES ($1, $2)
`

type AddOrganizationMemberParams struct {
	UserID         int32
	OrganizationID int32
}

func (q *Queries) AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) error {
	_, err := q.db.Exec(ctx, addOrganizationMember, arg.UserID, arg.OrganizationID)
	return err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name)
VALUES ($1)
RETURNING id, uid, name, created_at, updated_at
`

func (q *Queries) CreateOrganization(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByUID = `-- name: GetOrganizationByUID :one
SELECT id, uid, name, created_at, updated_at
FROM organizations
WHERE uid = $1
`

func (q *Queries) GetOrganizationByUID(ctx context.Context, uid pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByUID, uid)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isUserInOrganization = `-- name: IsUserInOrganization :one
SELECT id FROM organization_members
WHERE user_id = $1 AND organization_id = $2
`

type IsUserInOrganizationParams struct {
	UserID         int32
	OrganizationID int32
}

func (q *Queries) IsUserInOrganization(ctx context.Context, arg IsUserInOrganizationParams) (int32, error) {
	row := q.db.QueryRow(ctx, isUserInOrganization, arg.UserID, arg.OrganizationID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
