// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: share_links.sql

package db

import (
	"context"
)

const createShareLink = `-- name: CreateShareLink :one
INSERT INTO share_links (token, collection_id, created_by)
VALUES ($1, $2, $3)
RETURNING id, token, collection_id, access_count, created_by, created_at
`

type CreateShareLinkParams struct {
	Token        string
	CollectionID int32
	CreatedBy    int32
}

func (q *Queries) CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (ShareLink, error) {
	row := q.db.QueryRow(ctx, createShareLink, arg.Token, arg.CollectionID, arg.CreatedBy)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.CollectionID,
		&i.AccessCount,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteShareLinkByToken = `-- name: DeleteShareLinkByToken :exec
DELETE FROM share_links
WHERE token = $1
`

func (q *Queries) DeleteShareLinkByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteShareLinkByToken, token)
	return err
}

const getShareLinkByToken = `-- name: GetShareLinkByToken :one
SELECT id, token, collection_id, access_count, created_by, created_at
FROM share_links
WHERE token = $1
`

func (q *Queries) GetShareLinkByToken(ctx context.Context, token string) (ShareLink, error) {
	row := q.db.QueryRow(ctx, getShareLinkByToken, token)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.CollectionID,
		&i.AccessCount,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getShareLinksByCollectionID = `-- name: GetShareLinksByCollectionID :many
SELECT id, token, collection_id, access_count, created_by, created_at
FROM share_links
WHERE collection_id = $1
`

func (q *Queries) GetShareLinksByCollectionID(ctx context.Context, collectionID int32) ([]ShareLink, error) {
	rows, err := q.db.Query(ctx, getShareLinksByCollectionID, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShareLink
	for rows.Next() {
		var i ShareLink
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.CollectionID,
			&i.AccessCount,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementAccessCount = `-- name: IncrementAccessCount :one
UPDATE share_links
SET access_count = access_count + 1
WHERE token = $1
RETURNING id, token, collection_id, access_count, created_by, created_at
`

func (q *Queries) IncrementAccessCount(ctx context.Context, token string) (ShareLink, error) {
	row := q.db.QueryRow(ctx, incrementAccessCount, token)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.CollectionID,
		&i.AccessCount,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
